import './globals.css';

import type { Metadata } from 'next';
import { Figtree } from 'next/font/google';
import { cookies } from 'next/headers';

import Footer from '@/components/common/footer';
import Header from '@/components/common/header';
import { Toaster } from '@/components/ui/sonner';
import { fetchWithAuth } from '@/lib/auth';

const figtree = Figtree({
  subsets: ['latin'],
  weight: ['300', '400', '500', '600', '700'],
  preload: true,
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function getUser() {
  const cookieStore = cookies();
  const accessToken = cookieStore.get('access_token')?.value;

  if (!accessToken) {
    return null;
  }

  const headers: HeadersInit = {
    cookie: `access_token=${accessToken}`,
  };

  const res = await fetchWithAuth('/api/user', { headers });

  if (!res.ok) {
    return null;
  }

  const contentType = res.headers.get('content-type');
  if (!contentType || !contentType.includes('application/json')) {
    return null;
  }

  try {
    const data = await res.json();
    return data ?? null;
  } catch {
    return null;
  }
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const user = await getUser();

  return (
    <html lang="en" suppressHydrationWarning>
      <body className={figtree.className}>
        <div className="flex min-h-screen flex-col">
          <Header user={user} />
          <main className="flex flex-1 flex-col">{children}</main>
          <Toaster />
          <Footer />
        </div>
      </body>
    </html>
  );
}
